#!/bin/bash

set -euo pipefail

#echo "Building launch container 🧰 "
echo "Building launch container (may take sometime to complete) " $'\360\237\222\276'
cmdOption=${1:-1}

if [ "${cmdOption}" == "-n" ]; then
	make docker-build &
	pid=$!
elif [ "${cmdOption}" == "-q" ]; then
	make docker-build 2>&1  > /dev/null && echo $? > ${HOME}/.kubesim/build-exit-code &
	pid=$!
elif [ "${cmdOption}" == "-h" ]; then
	echo "Help: "
	echo "-n - enable full output"
	echo "-q - disable build output"
        echo "-h - this help"
	exit
elif [ "${cmdOption}" == 1 ]; then
	echo "Missing command line option, for help (-h) use for details"
	exit 1
else
	echo "Invalid command line option, for help (-h) use for details"
	exit 1
fi

if [ "${cmdOption}" == "-q" ]; then
	spin='-\|/'
	i=0
	while kill -0 $pid 2>/dev/null
	do
		i=$(( (i+1) %4 ))
		printf "\r${spin:$i:1}"
		sleep .1
	done
else
	while kill -0 $pid 2>/dev/null
	do
		sleep .1
	done
fi

exitCode=$(cat ${HOME}/.kubesim/build-exit-code)

if [ "${exitCode}" == 0 ]; then
	#echo "Starting Kubesim launch container 🕰️ "
	echo "Starting Kubesim launch container " $'\360\237\220\263'
	make simulator
else
	echo "Error with build"
	exit 1
fi

